#!/usr/bin/env python3
"""Converts the Spleen 8x16 BDF font (BSD-2-Clause, Frederic Cambus) to a C header for the
in-headset menu: ASCII 32..126, 16 rows per glyph, one byte per row (MSB = left pixel).
usage: make_font.py fonts/spleen-8x16.bdf > ../quest/src/font8x16.h"""
import sys

glyphs, cur, bitmap = {}, None, None
for line in open(sys.argv[1]):
    parts = line.split()
    if not parts:
        continue
    if parts[0] == "ENCODING":
        cur = int(parts[1])
    elif parts[0] == "BITMAP":
        bitmap = []
    elif parts[0] == "ENDCHAR":
        glyphs[cur] = bitmap
        bitmap = None
    elif bitmap is not None:
        bitmap.append(int(parts[0], 16))

print("// Generated by tools/make_font.py from Spleen 8x16 (c) Frederic Cambus, BSD-2-Clause.")
print("// ASCII 32..126, 8x16 cells, one byte per row (MSB = left).")
print("#pragma once")
print("static const unsigned char kFont8x16[95][16] = {")
for c in range(32, 127):
    rows = (glyphs.get(c, [0] * 16) + [0] * 16)[:16]
    print("  {" + ",".join(f"0x{r:02x}" for r in rows) + "},")
print("};")
