// Renders ASCII 32..126 from Menlo into 8x16 one-bit cells and prints a C header.
import AppKit
let W = 8, H = 16
var out = "// Generated by tools/make_font.swift: ASCII 32..126, 8x16 cells, one byte per row (MSB = left).\n#pragma once\nstatic const unsigned char kFont8x16[95][16] = {\n"
let font = NSFont(name: "Menlo-Bold", size: 13)!
for c in 32...126 {
    let rep = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: W, pixelsHigh: H, bitsPerSample: 8, samplesPerPixel: 1, hasAlpha: false, isPlanar: false, colorSpaceName: .deviceWhite, bytesPerRow: W, bitsPerPixel: 8)!
    NSGraphicsContext.saveGraphicsState()
    NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: rep)
    NSColor.black.setFill(); NSRect(x: 0, y: 0, width: W, height: H).fill()
    let s = String(UnicodeScalar(UInt8(c))) as NSString
    s.draw(at: NSPoint(x: 0, y: 1), withAttributes: [.font: font, .foregroundColor: NSColor.white])
    NSGraphicsContext.restoreGraphicsState()
    var rows: [String] = []
    for y in 0..<H {
        var b = 0
        for x in 0..<W where rep.bitmapData![y * W + x] > 100 { b |= 0x80 >> x }
        rows.append(String(format: "0x%02x", b))
    }
    out += "  {" + rows.joined(separator: ",") + "},\n"
}
out += "};\n"
print(out, terminator: "")
